# Generated by Django 4.1 on 2022-08-29 11:49

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(verbose_name='ФИО покупателя')),
                ('customer_address', models.TextField(verbose_name='Адрес')),
                ('customer_city', models.TextField(verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Описание покупателя',
                'verbose_name_plural': 'Описание покупателей',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название картины')),
                ('cost', models.TextField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Доступные картины',
                'verbose_name_plural': 'Доступные картины',
                'db_table': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='SoldPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.customer', verbose_name='Идентификатор покупателя')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pictures', verbose_name='Идентификатор картины')),
            ],
            options={
                'verbose_name': 'Проданные картины',
                'verbose_name_plural': 'Проданные картины',
                'db_table': 'sold_pictures',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField(verbose_name='Описание заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение')),
                ('order_status', models.TextField(validators=[app.models.status_validator], verbose_name='Статус заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.customer', verbose_name='Покупатель')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.soldpictures', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
    ]
